version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - java -version
      - mvn -version

  build:
    commands:
      - echo "Building application shaded JAR..."
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "Deploying target/original-aws-lambda-crud-1.0-SNAPSHOT.jar to AWS Lambda..."
      - aws lambda update-function-code --function-name course-service --zip-file fileb://target/original-aws-lambda-crud-1.0-SNAPSHOT.jar
      - echo "Deployment complete!"

artifacts:
  files:
    - target/original-aws-lambda-crud-1.0-SNAPSHOT.jar
  discard-paths: yes
